import { ComponentDefinitionRead } from '../models';

/**
 * Client-side fallbacks for the generic palette components. Merged by
 * `ComponentDefinitionStoreService`; backend definitions win when present.
 */

const INPUT_TYPE_OPTIONS = [
  'text',
  'email',
  'password',
  'number',
  'phone',
  'url',
  'textarea',
  'checkbox',
  'toggle',
  'dropdown',
  'radio',
  'date',
  'file',
];

const USER_INPUT: ComponentDefinitionRead = {
  id: 'builtin:user_input',
  type: 'user_input',
  label: 'User Input',
  icon: 'text_fields',
  category: 'Basic Fields',
  is_container: false,
  default_props: {
    label: 'User Input',
    placeholder: 'Enter value…',
    inputType: 'text',
    required: false,
    unique: false,
    defaultValue: '',
    fieldKey: '',
    showToggle: true,
    options: ['Option 1', 'Option 2'],
    rows: 4,
    minDate: '',
    maxDate: '',
    accept: 'image/*',
    multiple: false,
  },
  property_schema: [
    { key: 'inputType', label: 'Input type', inputType: 'select', options: INPUT_TYPE_OPTIONS },
    { key: 'label', label: 'Label', inputType: 'text', options: null },
    { key: 'placeholder', label: 'Placeholder', inputType: 'text', options: null },
    { key: 'fieldKey', label: 'Field Key (for saved data)', inputType: 'field_key', options: null },
    { key: 'required', label: 'Required', inputType: 'boolean', options: null },
    { key: 'unique', label: 'Must be unique', inputType: 'boolean', options: null },
    { key: 'defaultValue', label: 'Default Value', inputType: 'text', options: null },
    { key: 'showToggle', label: 'Show/Hide Toggle (password only)', inputType: 'boolean', options: null },
    { key: 'options', label: 'Options', inputType: 'list', options: null },
    { key: 'rows', label: 'Rows (textarea)', inputType: 'number', options: null },
    { key: 'minDate', label: 'Min Date', inputType: 'text', options: null },
    { key: 'maxDate', label: 'Max Date', inputType: 'text', options: null },
    { key: 'accept', label: 'Accepted file types', inputType: 'text', options: null },
    { key: 'multiple', label: 'Allow multiple files', inputType: 'boolean', options: null },
  ],
  created_at: '',
  updated_at: '',
};

const SOCIAL_PROVIDERS = [
  'google',
  'facebook',
  'twitter',
  'microsoft',
  'github',
  'apple',
  'linkedin',
];

const BUTTON: ComponentDefinitionRead = {
  id: 'builtin:button',
  type: 'button',
  label: 'Button',
  icon: 'smart_button',
  category: 'Actions',
  is_container: false,
  default_props: {
    label: 'Click Me',
    variant: 'primary',
    appearance: 'button',
    providers: ['google'],
    action: { actionType: 'none' },
  },
  property_schema: [
    { key: 'label', label: 'Label', inputType: 'text', options: null },
    {
      key: 'appearance',
      label: 'Appearance',
      inputType: 'select',
      options: ['button', 'link', 'social'],
    },
    {
      key: 'variant',
      label: 'Variant',
      inputType: 'select',
      options: ['primary', 'secondary', 'outline', 'danger'],
    },
    {
      key: 'providers',
      label: 'Social providers',
      inputType: 'checkbox_group',
      options: SOCIAL_PROVIDERS,
    },
  ],
  created_at: '',
  updated_at: '',
};

const TEXT_BLOCK: ComponentDefinitionRead = {
  id: 'builtin:text_block',
  type: 'text_block',
  label: 'Text',
  icon: 'title',
  category: 'Layout',
  is_container: false,
  default_props: {
    textType: 'body',
    content: 'Text content',
    binding: '',
    align: 'left',
    color: '#333333',
    fontSize: 16,
    fontWeight: 'normal',
    textAlign: 'left',
  },
  property_schema: [
    {
      key: 'textType',
      label: 'Text type',
      inputType: 'select',
      options: ['h1', 'h2', 'h3', 'h4', 'body', 'label'],
    },
    { key: 'content', label: 'Content', inputType: 'text', options: null },
    { key: 'binding', label: 'Formula (bind to variables)', inputType: 'formula', options: null },
    {
      key: 'align',
      label: 'Alignment (headings)',
      inputType: 'select',
      options: ['left', 'center', 'right'],
    },
    { key: 'color', label: 'Color', inputType: 'color', options: null },
    { key: 'fontSize', label: 'Font Size', inputType: 'number', options: null },
    {
      key: 'fontWeight',
      label: 'Font Weight',
      inputType: 'select',
      options: ['normal', '600', 'bold'],
    },
    {
      key: 'textAlign',
      label: 'Text Align',
      inputType: 'select',
      options: ['left', 'center', 'right'],
    },
  ],
  created_at: '',
  updated_at: '',
};

const MEDIA: ComponentDefinitionRead = {
  id: 'builtin:media',
  type: 'media',
  label: 'Media',
  icon: 'image',
  category: 'Branding',
  is_container: false,
  default_props: {
    mediaType: 'image',
    src: '',
    alt: 'Image',
    fit: 'contain',
    initials: 'AB',
    shape: 'circle',
    size: 40,
    iconName: 'star',
    color: '#333333',
    url: '',
    title: '',
  },
  property_schema: [
    {
      key: 'mediaType',
      label: 'Media type',
      inputType: 'select',
      options: ['image', 'avatar', 'icon', 'video'],
    },
    { key: 'src', label: 'Image', inputType: 'image', options: null },
    { key: 'alt', label: 'Alt Text', inputType: 'text', options: null },
    {
      key: 'fit',
      label: 'Fit',
      inputType: 'select',
      options: ['contain', 'cover', 'fill'],
    },
    { key: 'initials', label: 'Initials (avatar fallback)', inputType: 'text', options: null },
    {
      key: 'shape',
      label: 'Shape',
      inputType: 'select',
      options: ['circle', 'square', 'rounded'],
    },
    { key: 'size', label: 'Size (px)', inputType: 'number', options: null },
    { key: 'iconName', label: 'Icon Name', inputType: 'text', options: null },
    { key: 'color', label: 'Color', inputType: 'color', options: null },
    { key: 'url', label: 'Video URL', inputType: 'text', options: null },
    { key: 'title', label: 'Video Title', inputType: 'text', options: null },
  ],
  created_at: '',
  updated_at: '',
};

const CONTAINER: ComponentDefinitionRead = {
  id: 'builtin:container',
  type: 'container',
  label: 'Container',
  icon: 'view_agenda',
  category: 'Layout',
  is_container: true,
  default_props: {
    containerType: 'section',
    label: '',
    backgroundColor: '#ffffff',
    backgroundImage: '',
    padding: 24,
    direction: 'column',
    gap: 12,
  },
  property_schema: [
    {
      key: 'containerType',
      label: 'Container type',
      inputType: 'select',
      options: ['section', 'header', 'footer', 'sidebar', 'row', 'card', 'page'],
    },
    { key: 'label', label: 'Label', inputType: 'text', options: null },
    { key: 'backgroundColor', label: 'Background Color', inputType: 'color', options: null },
    { key: 'backgroundImage', label: 'Background Image', inputType: 'image', options: null },
    { key: 'padding', label: 'Padding (px)', inputType: 'number', options: null },
    {
      key: 'direction',
      label: 'Layout Direction',
      inputType: 'select',
      options: ['column', 'row'],
    },
    { key: 'gap', label: 'Gap (px)', inputType: 'number', options: null },
  ],
  created_at: '',
  updated_at: '',
};

const DISPLAY: ComponentDefinitionRead = {
  id: 'builtin:display',
  type: 'display',
  label: 'Display',
  icon: 'label',
  category: 'Display',
  is_container: false,
  default_props: {
    displayType: 'badge',
    text: 'Badge',
    tone: 'neutral',
    thickness: 1,
    style: 'solid',
    color: '#e5e7eb',
    height: 24,
    value: 60,
    max: 100,
    label: '',
    items: ['Item 1', 'Item 2'],
  },
  property_schema: [
    {
      key: 'displayType',
      label: 'Display type',
      inputType: 'select',
      options: ['badge', 'divider', 'spacer', 'progress', 'rating', 'list'],
    },
    { key: 'text', label: 'Text', inputType: 'text', options: null },
    {
      key: 'tone',
      label: 'Tone',
      inputType: 'select',
      options: ['neutral', 'success', 'warning', 'danger', 'info'],
    },
    { key: 'thickness', label: 'Thickness (px)', inputType: 'number', options: null },
    {
      key: 'style',
      label: 'Line Style',
      inputType: 'select',
      options: ['solid', 'dashed', 'dotted'],
    },
    { key: 'color', label: 'Color', inputType: 'color', options: null },
    { key: 'height', label: 'Height (px)', inputType: 'number', options: null },
    { key: 'value', label: 'Value', inputType: 'number', options: null },
    { key: 'max', label: 'Max', inputType: 'number', options: null },
    { key: 'label', label: 'Label', inputType: 'text', options: null },
    { key: 'items', label: 'Items', inputType: 'list', options: null },
  ],
  created_at: '',
  updated_at: '',
};

const WIDGET: ComponentDefinitionRead = {
  id: 'builtin:widget',
  type: 'widget',
  label: 'Widget',
  icon: 'widgets',
  category: 'Advanced',
  is_container: false,
  default_props: {
    widgetType: 'data_table',
    title: '',
    sourceType: 'entity',
    sourceEntityId: '',
    sourcePageId: '',
    pageSize: 50,
    links: ['Home', 'About'],
    tabs: ['Tab 1', 'Tab 2'],
    items: ['Item 1', 'Item 2'],
    steps: ['Step 1', 'Step 2'],
  },
  property_schema: [
    {
      key: 'widgetType',
      label: 'Widget type',
      inputType: 'select',
      options: ['data_table', 'kanban', 'navbar', 'tabs', 'accordion', 'stepper', 'breadcrumb'],
    },
    { key: 'title', label: 'Title', inputType: 'text', options: null },
    { key: 'sourceType', label: 'Data source', inputType: 'select', options: ['entity', 'page'] },
    { key: 'sourceEntityId', label: 'Source Entity (table)', inputType: 'entity_select', options: null },
    { key: 'sourcePageId', label: 'Source Page', inputType: 'page_select', options: null },
    { key: 'pageSize', label: 'Rows per Page', inputType: 'number', options: null },
    { key: 'links', label: 'Links', inputType: 'list', options: null },
    { key: 'tabs', label: 'Tabs', inputType: 'list', options: null },
    { key: 'items', label: 'Items', inputType: 'list', options: null },
    { key: 'steps', label: 'Steps', inputType: 'list', options: null },
  ],
  created_at: '',
  updated_at: '',
};

export const BUILTIN_COMPONENT_DEFINITIONS: ComponentDefinitionRead[] = [
  USER_INPUT,
  BUTTON,
  TEXT_BLOCK,
  MEDIA,
  CONTAINER,
  DISPLAY,
  WIDGET,
];
